version: '3.8'

services:
  mysql-courses:
    image: mysql:8.0
    container_name: mysql-courses
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: learnify_courses
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-courses:/var/lib/mysql
    networks:
      - app-network

  mysql-users:
    image: mysql:8.0
    container_name: mysql-users
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: learnify_users
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-users:/var/lib/mysql
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mysql-courses:
  mysql-users:
