version: '3.9'

services:
  mysql-course:
    image: mysql:8.0
    container_name: mysql-course
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: learnify
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-courses-data:/var/lib/mysql

  mysql-users:
    image: mysql:8.0
    container_name: mysql-users
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: learnify
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-users-data:/var/lib/mysql


  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-data:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-data

  keycloak-data:
      image: postgres:15
      container_name: keycloak-data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      volumes:
        - keycloak_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_LOG_RETENTION_HOURS: 168
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./kafka1-data:/var/lib/kafka/data

  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_LOG_RETENTION_HOURS: 168
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    volumes:
      - ./kafka2-data:/var/lib/kafka/data

volumes:
  mysql-users-data:
  mysql-courses-data:
  keycloak_data:
